### ISSUE TITLE
Fork using different license

### ISSUE THREAD

**Issue by bluecmd** [ryancbutler/ns-letsencrypt#12]
Hi,

I was told that there is a fork of this project, https://github.com/sideshowcecil/ns-letsencrypt which claims to be MIT license.

It doesn't mention anything about getting your permission to become MIT, and doesn't have any issues enabled so can't ask @sideshowcecil about this.

Before using the fork I'd like to be sure the license is actually MIT and that every author who's code is in the fork has authorized this.

Thanks

**Comment by ryancbutler** [comment]
Thanks for verifying.  I'm not the best when it comes to licensing but I'm totally fine with what @sideshowcecil is doing.  Glad to see it being adopted and seeing it evolve!  Just out of curiosity where did you find out about the fork?

**Comment by bluecmd** [comment]
Thanks for verifying!

It was a colleague that found out about the fork, I don't know exactly how he found it but I'd guess from the network tab on GitHub where you can see active forks.

**Comment by sideshowcecil** [comment]
Hey gents,

sorry for getting back quite late on this one.

When I first forked the project the license did not change, but when I decided to do a full rewrite I went ahead and changed it (I have to admit I didn't really think this one through too much).
Thanks @ryancbutler for approving my actions, next time I will be more considerate when it comes to this kind of changes.

Cheers
