### ISSUE TITLE
Link NetScaler certificate fails

### ISSUE THREAD

**Issue by alexsuppanz** [ryancbutler/ns-letsencrypt#5]
Hi,

We are currently running NS 12.1 and experienced an issue while renewing LetsEncrypt Certificates several weeks ago. Running ns-cronjob.sh creates the following output:

> LOGOUT: Created
>  + Requesting certificate...
>  + Checking certificate...
>  + Done!
>  + Creating fullchain.pem...
>  + Using cached chain!
> Creating Netscaler Certificate
> CREATING le-cert-my-domain.pem: Conflict
> CREATING le-privkey-my-domain.pem: Conflict
> Create Netscaler CERT: Netscaler specific error
> Using existing CA
> Link Netscaler CERTS: Netscaler specific error
> LOGOUT: Created
>  + Done!
> Saving Netscaler Configuration
> SAVE NS: OK
> LOGOUT: Created
>  INFO: Using main config file /root/ns-letsencrypt/config.sh_

When creating a certificate on the NetScaler using the created cert and key file, NetScaler requires to enter a password (it can be any random string with lower and upper case caracters, one numeric character and one special character). This leds me to the idea, that also via NITRO a password is required.
To investigate this issue, I edited ns-copytons.py and added **response.text** at the end of all affected functions to display NetScalers error output. This is the output I got from a simple test script:

> _Create Netscaler CERT: Netscaler specific error
> { "errorcode": 1537, "message": "Invalid private key, or PEM pass phrase required for this private key", "severity": "ERROR" }_

To resolve this issue, I added a new line into **mynsconfig.py** 
`passplain = "#V3ryC0mplexPassword123#"`

and edited the function **createSSL** as in **ns-copytons.py** follows

```
 _def createSSL(connectiontype,nitroNSIP,authToken, nscert, nspairname, nskey):
   url = '%s://%s/nitro/v1/config/sslcertkey' % (connectiontype, nitroNSIP)
   headers = {'Content-type': 'application/json','Cookie': authToken}
   json_string = {
   "sslcertkey": {
       "certkey": nspairname,
       "cert": nscert,
       "key": nskey,
       "passplain": passplain,
       "password": True,}
   }
   payload = json.dumps(json_string)
   response = requests.post(url, data=payload, headers=headers, verify=False)
   print "Create Netscaler CERT: %s" % response.reason
   print nspairname
   print response.text
```
This adds the required password to create the server certificate into the request payload a well as prints the return output for easier troubleshooting.

# Length of certificate name is limited to 31 characters
Since the script prepends _le-certificate-_ to each server certificate, these names can be long, and when having long domain names, even too long for NetScaler. This is the error it generates:

> { "errorcode": 1106, "message": "String length exceeds maximum [certkeyName, 31]", "severity": "ERROR" }

The above function will also print this error in case some of you also run into this issue. As an immediate workaround in **mynsconfig.py** I edited the pair name prefix to

```
#Pair Name Prefix (le-certificate-mydomain)
nspairname = "le"
```

@ryancbutler Please update all affected files, if you agree to this changes!

Kind regards,
Alex

**Comment by ryancbutler** [comment]
#6
