### ISSUE TITLE
Request failed

### ISSUE THREAD

**Issue by Makrador** [ryancbutler/ns-letsencrypt#9]
Hi,

when I start the script i get this output...:

UNBIND RESPONDER POLICY: OK
LOGOUT: Created
 + Challenge validation has failed :(
ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:unauthorized",
    "detail": "Invalid response from http://xxx.xxxx.xx/.well-known/acme-challenge/xMeM0tzwpWFHgh8WWg9s4zqwd_RaD_pvzALV-CH4ou0 [x.x.x.x]: 404",
    "status": 403
  },
  "uri": "https://acme-staging.api.letsencrypt.org/acme/chall-v3/9265759/eePUvw",
  "token": "xMeM0tzwpWFHgh8WWg9s4zqwd_RaD_pvzALV-CH4ou0",
  "validationRecord": [
    {
      "url": "http://xxx.xxx.xx/.well-known/acme-challenge/xMeM0tzwpWFHgh8WWg9s4zqwd_RaD_pvzALV-CH4ou0",
      "hostname": "xx.xxxx.xx",
      "port": "80",
      "addressesResolved": [
        "x.x.x.x"
      ],
      "addressUsed": "x.x.x.x"
    }
  ]
})
Saving Netscaler Configuration
SAVE NS: OK
LOGOUT: Created
# INFO: Using main config file /root/ns-letsencrypt/config.sh

the personal infos got replaced by x

After I used tcpdump I see that lets encrypt starts a request that the Netscaler didn't answer...
That request gets repeated 3 times from differnet ip-adresses....

Any Ideas ?

**Comment by Makrador** [comment]
# INFO: Using main config file /root/ns-letsencrypt/config.sh
Testing Netscaler Connectivity
Connectivity To Netscaler OK
LOGOUT: Created
Processing xxx.xxx.de
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting authorization for xxx.xxx.de...
 + 1 pending challenge(s)
 + Deploying challenge tokens...
Creating Challenge Policy for xxx.xxx.de
CREATE RESPONDER ACTION: Created
CREATE RESPONDER POLICY: Created
BIND RESPONDER POLICY: OK
LOGOUT: Created
 + Responding to challenge for xxx.xxx.de authorization...
 + Cleaning challenge tokens...
Removing Challenge Policy for xxx.xxx.de
UNBIND RESPONDER POLICY: OK
DELETE RESPONDER POLICY: OK
DELETE RESPONDER ACTION: OK
LOGOUT: Created
 + Challenge validation has failed :(
ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:connection",
    "detail": "Fetching http://xxx.xxx.de/.well-known/acme-challenge/XqiiV-h2y9MzKGddkix55DNKVasm7lqAR4TAQFuNz6Q: Timeout during connect (likely firewall problem)",
    "status": 400
  },
  "uri": "https://acme-staging.api.letsencrypt.org/acme/chall-v3/15134113/jQu7sQ",
  "token": "XqiiV-h2y9MzKGddkix55DNKVasm7lqAR4TAQFuNz6Q",
  "validationRecord": [
    {
      "url": "http://xxx.xxx.de/.well-known/acme-challenge/XqiiV-h2y9MzKGddkix55DNKVasm7lqAR4TAQFuNz6Q",
      "hostname": "xxx.xxx.de",
      "port": "80",
      "addressesResolved": [
        "x.x.x.x"
      ],
      "addressUsed": "xxx.xxx.xxx.xxx"
    }
  ]
})
Saving Netscaler Configuration
SAVE NS: OK
LOGOUT: Created
# INFO: Using main config file /root/ns-letsencrypt/config.sh

**Comment by crzfst** [comment]
"urn:acme:error:connection" - you have to upgrade dehydrated to latest version in order to fix this error.

**Comment by ryancbutler** [comment]
Is this still an issue?
